name: Parse Biedronka Offers

on:
  workflow_dispatch:

jobs:
  parse-offers:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies and run script
      run: |
        make all

    - name: Commit and push if there are changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add offers.json
        git commit -m "Update offers" || echo "No changes to commit"
        git push
